services:
  db:
    image: mariadb
    container_name: mariadb-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
    ports: 
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer-server
    restart: always
    ports:
      - "8080:8080"